#!/usr/bin/env bash

GIT_DIR=$(git rev-parse --git-dir)
PROJECT_ROOT="$(git rev-parse --show-toplevel)"

echo "Installing hooks..."
# this command creates symlink to our pre-push script
if test -f "$GIT_DIR"/hooks/pre-push; then
    rm "$GIT_DIR"/hooks/pre-push
fi

ln -s "$PROJECT_ROOT"/.git_hooks/pre-push "$GIT_DIR"/hooks/pre-push
echo "Done!"
