#!/usr/bin/env bash

GIT_DIR=$(git rev-parse --git-dir)

echo "Installing hooks..."
# this command creates symlink to our pre-push script
rm "$GIT_DIR"/hooks/pre-push

ln ./pre-push "$GIT_DIR"/hooks/pre-push
echo "Done!"
